apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mediumclone-project
  name: mediumclone-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediumclone-project
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mediumclone-project
    spec:
      containers:
      - image: matheusrbraga/mc-image
        name: mc-image
        ports:
        - containerPort: 3000
        resources: {}
status: {}
